-- 1
SELECT CITY, DEPARTMENT_NAME, COUNT(DEPARTMENT_ID) FROM LOCATIONS JOIN DEPARTMENTS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID GROUP BY CITY, DEPARTMENT_NAME;

SELECT CITY, DEPARTMENT_NAME, COUNT(DEPARTMENT_ID) FROM LOCATIONS NATURAL JOIN DEPARTMENTS GROUP BY CITY, DEPARTMENT_NAME;

-- 2

SELECT CITY, DEPARTMENT_NAME, COUNT(DEPARTMENT_ID) FROM LOCATIONS FULL JOIN DEPARTMENTS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID GROUP BY CITY, DEPARTMENT_NAME;

-- 3

SELECT CITY, DEPARTMENT_NAME, COUNT(DEPARTMENT_ID) FROM LOCATIONS FULL JOIN DEPARTMENTS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID GROUP BY CITY, DEPARTMENT_NAME HAVING COUNT(DEPARTMENT_ID) > 1;

--4

SELECT DEPARTMENT_NAME, COUNTRY_NAME, COUNT(EMPLOYEE_ID) AS NUM_EMPLEATS, AVG(SALARY) AS MITJA_SALARI, SUM(SALARY) AS SUM_SALARI FROM COUNTRIES JOIN LOCATIONS ON COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID JOIN DEPARTMENTS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID GROUP BY DEPARTMENT_NAME, COUNTRY_NAME ORDER BY COUNTRY_NAME ASC, AVG(SALARY) DESC;

SELECT DEPARTMENT_NAME, COUNTRY_NAME, COUNT(EMPLOYEE_ID) AS NUM_EMPLEATS, AVG(SALARY) AS MITJA_SALARI, SUM(SALARY) AS SUM_SALARI FROM COUNTRIES NATURAL JOIN LOCATIONS NATURAL JOIN DEPARTMENTS JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID GROUP BY DEPARTMENT_NAME, COUNTRY_NAME ORDER BY COUNTRY_NAME ASC, AVG(SALARY) DESC;

-- 5

SELECT DEPARTMENT_NAME, COUNTRY_NAME, COUNT(EMPLOYEE_ID) AS NUM_EMPLEATS, AVG(SALARY) AS MITJA_SALARI, SUM(SALARY) AS SUM_SALARI FROM COUNTRIES JOIN LOCATIONS ON COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID JOIN DEPARTMENTS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID RIGHT JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID GROUP BY DEPARTMENT_NAME, COUNTRY_NAME ORDER BY COUNTRY_NAME ASC, AVG(SALARY) DESC;

SELECT DEPARTMENT_NAME, COUNTRY_NAME, COUNT(EMPLOYEE_ID) AS NUM_EMPLEATS, AVG(SALARY) AS MITJA_SALARI, SUM(SALARY) AS SUM_SALARI FROM COUNTRIES NATURAL JOIN LOCATIONS NATURAL JOIN DEPARTMENTS RIGHT JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID GROUP BY DEPARTMENT_NAME, COUNTRY_NAME ORDER BY COUNTRY_NAME ASC, AVG(SALARY) DESC;

-- 6

SELECT COUNTRY_NAME, COUNT(EMPLOYEE_ID) AS NUM_EMPLEATS FROM COUNTRIES JOIN LOCATIONS ON COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID JOIN DEPARTMENTS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID GROUP BY COUNTRY_NAME;

SELECT COUNTRY_NAME, COUNT(EMPLOYEE_ID) AS NUM_EMPLEATS FROM COUNTRIES NATURAL JOIN LOCATIONS NATURAL JOIN DEPARTMENTS JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID GROUP BY COUNTRY_NAME;

-- 7

SELECT COUNTRY_NAME, COUNT(EMPLOYEE_ID) AS NUM_EMPLEATS FROM COUNTRIES LEFT JOIN LOCATIONS ON COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID LEFT JOIN DEPARTMENTS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID LEFT JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID GROUP BY COUNTRY_NAME;

SELECT COUNTRY_NAME, COUNT(EMPLOYEE_ID) AS NUM_EMPLEATS FROM COUNTRIES NATURAL LEFT JOIN LOCATIONS NATURAL LEFT JOIN DEPARTMENTS LEFT JOIN EMPLOYEES ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID GROUP BY COUNTRY_NAME;

--8

SELECT EMP.FIRST_NAME || ' ' || EMP.LAST_NAME AS NOM, EMP.HIRE_DATE AS DATA_CONTRACTE, MAN.FIRST_NAME || ' ' || MAN.LAST_NAME AS CAP, DEPARTMENT_NAME AS NOM_DEPARTAMENT, JOB_TITLE AS OCUPACIO FROM EMPLOYEES EMP RIGHT JOIN EMPLOYEES MAN ON EMP.EMPLOYEE_ID = MAN.MANAGER_ID JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = MAN.DEPARTMENT_ID JOIN JOBS ON JOBS.JOB_ID = MAN.JOB_ID;

-- 9

SELECT FIRST_NAME || ' ' || LAST_NAME AS NOM,TO_CHAR(START_DATE, 'DD MONTH YYYY') AS DATA_INICI, TO_CHAR(END_DATE, 'DD MON YYYY') AS DATA_FI, DEPARTMENT_NAME AS DEPARTAMENT, JOB_TITLE AS OCUPACIO FROM EMPLOYEES JOIN JOB_HISTORY ON EMPLOYEES.EMPLOYEE_ID = JOB_HISTORY.EMPLOYEE_ID JOIN DEPARTMENTS ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID JOIN JOBS ON JOBS.JOB_ID = EMPLOYEES.JOB_ID ORDER BY TO_CHAR(START_DATE, 'DD MONTH YYYY') ASC, FIRST_NAME || ' ' || LAST_NAME ASC;

-- 10

SELECT DEPARTMENT_NAME AS DEPARTAMENT, FIRST_NAME || ' ' || LAST_NAME AS NOM FROM DEPARTMENTS FULL JOIN EMPLOYEES ON DEPARTMENTS.MANAGER_ID = EMPLOYEES.MANAGER_ID;

