SELECT LOCATION_ID, DEPARTMENT_NAME, COUNT(*) FROM DEPARTMENTS GROUP BY LOCATION_ID, DEPARTMENT_NAME;

SELECT LOCATION_ID, DEPARTMENT_NAME,  COUNT(*) FROM DEPARTMENTS WHERE DEPARTMENT_NAME IS NULL GROUP BY LOCATION_ID, DEPARTMENT_NAME UNION SELECT LOCATION_ID, DEPARTMENT_NAME, COUNT(*) FROM DEPARTMENTS WHERE DEPARTMENT_NAME IS NOT NULL GROUP BY LOCATION_ID, DEPARTMENT_NAME;

SELECT LOCATION_ID, DEPARTMENT_NAME, COUNT(*) FROM DEPARTMENTS GROUP BY  LOCATION_ID, DEPARTMENT_NAME HAVING COUNT(*) > 1;

SELECT DEPARTMENT_NAME, COUNT(EMPLOYEE_ID) AS NUMERO_EMPLEATS, SUM(SALARY) AS SUMA_SALARIS, AVG(SALARY) AS MITJA_SALARIS FROM DEPARTMENTS, EMPLOYEES GROUP BY DEPARTMENT_NAME ORDER BY AVG(SALARY) DESC;


